### ISSUE TITLE
Slow spam

### ISSUE THREAD

**Issue by enigmatic21** [Sitiaro/Discord-spambot#1]
The speed of the spam is slow. Is there any ways to increase the spam speed? A way for the bot to support multiple logins maybe? Anything would help.

**Comment by Sitiaro** [comment]
The spam speed is totally depended on how fast your internet connection or the server that you're hosting your bot on is. I didn't use a time module or anything for a specific reason. As for the multiple login support option, that won't work either, unless you open a new terminal window, change the bot's token and run it again. I tried stacking client.run( ) just to test this and it only ran the first bot. Even so, I'll look into this and add it to the bot if I'm able to find anything useful that could help with this.

**Comment by enigmatic21** [comment]
Can I not do something like this right below the first code?

client1 = discord.Client()
trigger1 = 'spam'
length1 = len(trigger1)

@client.event
async def on_message(message):
    for i in range(length1):
        if trigger[i] in message.content:
            for j in range(10):
                await message.channel.send("Spam test")

client.run("TOKEN_HERE")

**Comment by Sitiaro** [comment]
Why not give it a try?

**Comment by enigmatic21** [comment]
Ok that didn't work, I tried running several bots and they produced a massive lag so that's a fix but can you make an anti-raid bot too? That'll be a great help.

**Comment by Sitiaro** [comment]
Already did, check https://github.com/Sitiaro/antispamdisc
